### ISSUE TITLE
Difficulty with my Public URL

### ISSUE THREAD

**Issue by tbrooke** [futurice/metalsmith-prismic-template#19]
I am looking at the template for use in my nonprofit cite and I am using a public prismic repository that should not need the token nor the secret

I get the error message:  Cannot GET /

URLS work from the browser

PRISMIC_URL=https://metalsmith-prismic-template.prismic.io/api  <= This Works

This one has the cdn and returns json:
PRISMIC_URL=https://mainstmission.cdn.prismic.io/api    <= This does Not Work

Thinking the cdn might be the problem I tried this one without cdnc and it returns the query form
PRISMIC_URL=https://speedlaw.prismic.io/api <= This does Not Work

**Comment by kiia** [comment]
There's an issue for this already in the metalsmith-prismic-server repo https://github.com/futurice/metalsmith-prismic-server/issues/13. Setting the PRISMIC_TOKEN to null should fix the issue.
